vim.opt.number = true               -- Show line numbers
vim.opt.relativenumber = true       -- Relative line numbers
vim.opt.tabstop = 2                 -- A tab is 2 spaces wide
vim.opt.softtabstop = 2             -- Tab behaves like 2 spaces when editing
vim.opt.shiftwidth = 2              -- Indentation uses 2 spaces per tab
vim.opt.expandtab = false           -- ❌ Do NOT convert tabs to spaces (use real tabs)
vim.opt.termguicolors = true        -- Enable true color
vim.opt.ignorecase = true           -- Ignore case when searching
vim.opt.smartcase = true            -- Be case-sensitive when capital letters are used
vim.opt.clipboard = "unnamedplus"   -- Use system clipboard
vim.opt.cursorline = true           -- Highlight the current line
vim.opt.scrolloff = 5               -- Keep cursor in view
vim.opt.wrap = false                -- Disable line wrapping
