local function toggle_checkbox()
	if vim.bo.filetype == "markdown" then
		require("obsidian").util.toggle_checkbox()
	end
end

local function generate_daily_note(day_offset, label)
	return function()
		local script_path = vim.fn.expand("~/Documents/notes/.scripts/generate_daily_note.py")
		vim.system(
			{ "python3", script_path, tostring(day_offset) },
			{ text = true },
			vim.schedule_wrap(function(obj)
				if obj.code == 0 then
					for _, line in ipairs(vim.split(obj.stdout, "\n")) do
						local file_path = line:match("FILE_PATH:(.*)")
						if file_path then
							vim.cmd("edit " .. vim.fn.fnameescape(file_path))
							return
						end
					end
				else
					vim.notify("Failed to generate " .. label .. ": " .. obj.stderr, vim.log.levels.ERROR)
				end
			end)
		)
	end
end

return {
	"obsidian-nvim/obsidian.nvim", -- Community fork with modern picker support
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"nvim-treesitter/nvim-treesitter", -- Better markdown parsing
	},
	lazy = true,
	ft = "markdown",
	opts = {
		workspaces = {
			{ name = "brain", path = "~/Documents/notes" },
		},

		notes_subdir = "0-inbox",

		-- Disable UI for performance, use render-markdown.nvim instead
		ui = { enable = false },

		legacy_commands = false,

		completion = {
			nvim_cmp = false,
			min_chars = 2,
		},

		picker = {
			name = "telescope.nvim",
		},

		-- Human-readable note IDs that match the vault naming scheme
		note_id_func = function(title)
			local suffix = os.date("%Y%m%d%H%M")
			if title then
				local slug = title:lower():gsub("%s+", "-"):gsub("[^a-z0-9-]", "")
				slug = slug:gsub("-+", "-"):gsub("^-", ""):gsub("-$", "")
				return slug ~= "" and slug or suffix
			else
				return suffix
			end
		end,

		-- Route new notes into the inbox by default.
		new_notes_location = "notes_subdir",

		link = {
			style = "wiki",
		},

		-- Daily notes are generated by the Python script.
		daily_notes = {
			folder = "journal",
			date_format = "%Y-%m-%d",
			alias_format = "%B %-d, %Y",
			-- template = "daily", -- Disabled: Use Python script for date-aware generation
		},

		templates = {
			folder = "templates",
			date_format = "%Y-%m-%d",
			time_format = "%H:%M",
			-- Substitutions for templates
			substitutions = {
				yesterday = function()
					return os.date("%Y-%m-%d", os.time() - 86400)
				end,
				tomorrow = function()
					return os.date("%Y-%m-%d", os.time() + 86400)
				end,
			},
		},

		-- Attachments configuration (for images, PDFs, etc.)
		attachments = {
			folder = "assets/images",
			---@param client obsidian.Client
			---@param path obsidian.Path the absolute path to the image file
			---@return string
			img_text_func = function(client, path)
				path = client:vault_relative_path(path) or path
				return string.format("![%s](%s)", path.name, path)
			end,
		},

		-- Enable additional markdown features
		frontmatter = {
			enabled = true,
			func = function(note)
				local out = {
					id = note.id,
					aliases = note.aliases,
					tags = note.tags,
					created = os.date("%Y-%m-%d %H:%M"),
				}

				-- Add metadata for todos
				if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
					for k, v in pairs(note.metadata) do
						out[k] = v
					end
				end

				return out
			end,
		},

		-- Better search
		finder = "telescope.nvim",
		search = {
			sort_by = "modified",
			sort_reversed = true,
			max_lines = 1000,
		},
		open_notes_in = "current",
	},

	keys = {
		-- Existing keybindings
		{ "<leader>no", "<cmd>Obsidian open<cr>", desc = "Open in Obsidian" },
		{ "<leader>nn", "<cmd>Obsidian new<cr>", desc = "New Note" },
		{ "<leader>ns", "<cmd>Obsidian search<cr>", desc = "Search Vault" },
		{ "<leader>nf", "<cmd>Obsidian follow_link<cr>", desc = "Follow Link" },

		-- Enhanced workflow keybindings
		{ "<leader>nq", "<cmd>Obsidian quick_switch<cr>", desc = "Quick Switch Note" },
		{ "<leader>nb", "<cmd>Obsidian backlinks<cr>", desc = "Show Backlinks" },
		{ "<leader>nt", "<cmd>Obsidian tags<cr>", desc = "Search Tags" },
		{ "<leader>nl", "<cmd>Obsidian links<cr>", desc = "Show All Links" },

		-- Todo management
		{ "<leader>nT", "<cmd>Obsidian toc<cr>", desc = "Table of Contents" },
		{
			"<leader>nx",
			"<cmd>Obsidian extract_note<cr>",
			mode = "v",
			desc = "Extract to New Note",
		},

		-- Templates
		{ "<leader>nti", "<cmd>Obsidian template<cr>", desc = "Insert Template" },
		{ "<leader>ntd", "<cmd>Obsidian template decision<cr>", desc = "Decision Template" },
		{ "<leader>ntg", "<cmd>Obsidian template debug-log<cr>", desc = "Debug Template" },
		{ "<leader>ntl", "<cmd>Obsidian template learning<cr>", desc = "Learning Template" },
		{ "<leader>ntm", "<cmd>Obsidian template meeting<cr>", desc = "Meeting Template" },
		{ "<leader>ntp", "<cmd>Obsidian template project<cr>", desc = "Project Template" },
		{ "<leader>ntt", "<cmd>Obsidian template todo<cr>", desc = "Todo Template" },

		-- Quick capture workflows
		{
			"<leader>nm",
			function()
				-- Quick meeting note
				local title = "Meeting " .. os.date("%Y-%m-%d %H:%M")
				vim.cmd("Obsidian new " .. title)
			end,
			desc = "Quick Meeting Note",
		},
		{
			"<leader>ni",
			function()
				-- Quick idea capture
				local title = "Idea " .. os.date("%Y%m%d%H%M")
				vim.cmd("Obsidian new " .. title)
			end,
			desc = "Quick Idea",
		},

		-- Working with current file
		{ "<leader>nr", "<cmd>Obsidian rename<cr>", desc = "Rename Note" },
		{ "<leader>np", "<cmd>Obsidian paste_img<cr>", desc = "Paste Image" },

		-- Todo/checkbox management
		{
			"<leader>nc",
			toggle_checkbox,
			desc = "Toggle Checkbox",
		},

		-- Navigation (using Python script for date-aware generation)
		{
			"<leader>nd",
			generate_daily_note(0, "today's daily note"),
			desc = "Generate Today's Daily Note",
		},
		{
			"<leader>ny",
			generate_daily_note(-1, "yesterday's daily note"),
			desc = "Generate Yesterday's Daily Note",
		},
		{
			"<leader>nY",
			generate_daily_note(1, "tomorrow's daily note"),
			desc = "Generate Tomorrow's Daily Note",
		},
		{ "<leader>nD", "<cmd>Obsidian dailies<cr>", desc = "Browse Daily Notes" },

		-- Workspace management (if you add more workspaces later)
		{ "<leader>nw", "<cmd>Obsidian workspace<cr>", desc = "Switch Workspace" },
	},
	config = function(_, opts)
		require("obsidian").setup(opts)

		local group = vim.api.nvim_create_augroup("obsidian-local-keymaps", { clear = true })

		vim.api.nvim_create_autocmd("FileType", {
			group = group,
			pattern = "markdown",
			callback = function(event)
				local map = function(lhs, rhs, desc, mode)
					vim.keymap.set(mode or "n", lhs, rhs, {
						buffer = event.buf,
						desc = desc,
						silent = true,
					})
				end

				map("<localleader>o", "<cmd>Obsidian open<cr>", "Open in Obsidian")
				map("<localleader>b", "<cmd>Obsidian backlinks<cr>", "Show Backlinks")
				map("<localleader>l", "<cmd>Obsidian links<cr>", "Show Links")
				map("<localleader>t", "<cmd>Obsidian tags<cr>", "Search Tags")
				map("<localleader>r", "<cmd>Obsidian rename<cr>", "Rename Note")
				map("<localleader>p", "<cmd>Obsidian paste_img<cr>", "Paste Image")
				map("<localleader>c", toggle_checkbox, "Toggle Checkbox")
				map("<localleader>d", generate_daily_note(0, "today's daily note"), "Generate Today's Daily Note")
				map("<localleader>y", generate_daily_note(-1, "yesterday's daily note"), "Generate Yesterday's Daily Note")
				map("<localleader>Y", generate_daily_note(1, "tomorrow's daily note"), "Generate Tomorrow's Daily Note")
			end,
		})
	end,
}
