# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

# Audio bell
enable_audio_bell no

# Cursor blink
cursor_blink_interval 0
cursor_shape block
cursor_stop_blinking_after 0
shell_integration  no-cursor

# Fonts
include current-font.conf
font_size 10
modify_font cell_height 95%

# Remove OS title bar
hide_window_decorations titlebar-only

# Ensure no conflicting keyboard shortcuts
map ctrl+shift+= increase_font_size
map ctrl+shift+- decrease_font_size
map ctrl+shift+f reset_font_size

# ───────────────────────────────
# Tabs
# ───────────────────────────────
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# ───────────────────────────────
# Splits
# ───────────────────────────────
map ctrl+shift+d launch --location=split
map ctrl+shift+h neighboring_window left
map ctrl+shift+j neighboring_window down
map ctrl+shift+k neighboring_window up
map ctrl+shift+l neighboring_window right
map ctrl+shift+equal resize_window all 50 50
map ctrl+shift+space next_layout

# ───────────────────────────────
# Misc
# ───────────────────────────────
map ctrl+shift+f toggle_fullscreen
map ctrl+shift+m toggle_maximized
map ctrl+shift+p kitten hints
map ctrl+shift+r reload_config_file

# ───────────────────────────────
# Split creation
# ───────────────────────────────
map ctrl+shift+backslash launch --location=vsplit
map ctrl+shift+minus launch --location=hsplit

# ───────────────────────────────
# Tab Bar Styling
# ───────────────────────────────

tab_bar_edge top
tab_bar_align left
tab_bar_style separator
tab_bar_background #16161e
tab_bar_margin_width 8.0
tab_bar_margin_height 2.0 2.0
tab_bar_margin_color none
tab_bar_min_tabs 2

# Add padding inside each tab label
tab_title_template " {index}: {title} "

# Keep titles manageable
tab_title_max_length 30

# Colors
active_tab_background   #bb9af7
active_tab_foreground   #1a1b26
inactive_tab_background #1a1b26
inactive_tab_foreground #565f89

# Fonts
active_tab_font_style bold
inactive_tab_font_style normal

# Let you rename tabs
map ctrl+shift+n set_tab_title
